### ISSUE TITLE
Expectations to address

### ISSUE THREAD

**Issue by K3ra-y** [UBC-MDS/Sustainability_Survey#4]
- [x] Identify the question that survey will answer.
- [x]  Identify the other questions that is planned to ask in the survey to identify confounding variables and  justify/explain why we plan to include them.
- [x] Plan to analyze the survey results.
- [x] Discuss the aspects of [the UBC Office of Research Ethics document on Using Online Surveys](https://ethics.research.ubc.ca/sites/ore.ubc.ca/files/documents/Online_Survey-GN.pdf) that are relevant to our proposed survey.

**Comment by mchiriboga** [comment]
Items addressed on [Milestone 1 release](https://github.com/UBC-MDS/Sustainability_Survey/releases/tag/v1.0)
